server:
    port: 80

spring:
    datasource:
        url: ${DBMS_CONNECTION:jdbc:mysql://172.17.0.2:3306/shop_page}
        username: ${DBMS_USERNAME:root}
        password: ${DBMS_PASSWORD:root}
        driver-class-name: "com.mysql.cj.jdbc.Driver"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

open:
    api:
        title: SHOP PAGE API DOCUMENT
        version: v1.0.0
        description: Some basic api for main and detail shop page
        serverUrl: http://localhost:80
